画面遷移図
woony-nam/GraduationProject_RUNTEQ pull request #2
Opened 2024-09-28 05:24 UTC by woony-nam

### 画面遷移図
https://www.figma.com/board/4al43cGJZwYYX5fmAbBPqA/%E7%84%A1%E9%A1%8C?node-id=0-1&node-type=canvas&t=zK8tRn6Y3L3Q0tmh-0

### READMEに記載した機能
- [x] 会員登録へ進むボタン
- [x] 20歳以上確認画面
　- Yes/No ボタン
- [x] 会員登録機能
- [x] ログイン機能へ進むボタン
　- ログイン機能
- [x] マイページ 
- [x] 投稿一覧
- [x] 新規投稿作成ページ
- [x] 検索機能（ 題名 or 銘柄 or UserName）
- [x] 検索結果ページ

### MVPリリース後に取り組む機能
- [x] 投稿詳細ページ
　- 翻訳機能
　- いいね機能
　- いいね解除機能
- [x] 投稿主のProfileページ
　- 翻訳機能
- [x] 検索機能（Tag）
- [x] 検索結果ページ
- [x] メニューバー
- [x] いいね履歴確認機能
　- いいね解除機能
- [x] My投稿一覧ページ
- [x] My投稿詳細ページ
- [x] My投稿編集ページ
　- 題名
　- 銘柄
　- 5段階評価の感想
　- 写真
　- Tag
　- コメント
　- 削除
- [x] MyProfile確認ページ
- [x] MyProfile編集ページ
　- UserName
　- Birthdate
　- ProfilePhoto
　- 一言ステータス
- [x] MyProfile編集内容確認ページ
- [x] 編集完了ページ
- [x] アカウント削除機能
- [x] MailAddress/Password 変更機能(＊)
- [x] 新規投稿作成ページ（写真/Tag/コメント）

### 未ログインでも閲覧または利用できるページ
日本酒（アルコール）を扱う内容なので、未ログインでも利用できるページはありません。

### メールアドレス・パスワード変更確認項目
直接変更できるものではなく、一旦メールなどを介して専用のページで変更する画面遷移にします。
- [x] メールアドレス
- [x] パスワード

### 各画面の作り込み
- [x] 作り込みはある程度完了していると思います。（Figmaを見て画面の作成ができる状態）

2024-09-29 07:54 UTC, tarakish requested changes
URLにアクセスしましたが閲覧権限がなく見れなかったため権限の見直しをお願いします！
![スクリーンショット 2024-09-29 16 53 57](https://github.com/user-attachments/assets/31f856bf-11ff-4270-b5f9-3625fea6df05)

2024-09-30 01:50 UTC, woony-nam commented
大変失礼しました。
権限の設定を変更しました。

### 画面遷移図 https://www.figma.com/board/4al43cGJZwYYX5fmAbBPqA/%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB%E5%9B%B3?t=AzCZJhPN1oR3k02n-1

### READMEに記載した機能
- [x] 会員登録へ進むボタン
- [x] 20歳以上確認画面
　- Yes/No ボタン
- [x] 会員登録機能
- [x] ログイン機能へ進むボタン
　- ログイン機能
- [x] マイページ 
- [x] 投稿一覧
- [x] 新規投稿作成ページ
- [x] 検索機能（ 題名 or 銘柄 or UserName）
- [x] 検索結果ページ


### MVPリリース後に取り組む機能
- [x] 投稿詳細ページ
　- 翻訳機能
　- いいね機能
　- いいね解除機能
- [x] 投稿主のProfileページ
　- 翻訳機能
- [x] 検索機能（Tag）
- [x] 検索結果ページ
- [x] メニューバー
- [x] いいね履歴確認機能
　- いいね解除機能
- [x] My投稿一覧ページ
- [x] My投稿詳細ページ
- [x] My投稿編集ページ
　- 題名
　- 銘柄
　- 5段階評価の感想
　- 写真
　- Tag
　- コメント
　- 削除
- [x] MyProfile確認ページ
- [x] MyProfile編集ページ
　- UserName
　- Birthdate
　- ProfilePhoto
　- 一言ステータス
- [x] MyProfile編集内容確認ページ
- [x] 編集完了ページ
- [x] アカウント削除機能
- [x] MailAddress/Password 変更機能(＊)
- [x] 新規投稿作成ページ（写真/Tag/コメント）


### 未ログインでも閲覧または利用できるページ
日本酒（アルコール）を扱う内容なので、未ログインでも利用できるページはありません。

### メールアドレス・パスワード変更確認項目
直接変更できるものではなく、一旦メールなどを介して専用のページで変更する画面遷移にします。
- [x] メールアドレス
- [x] パスワード

### 各画面の作り込み
- [x] 作り込みはある程度完了していると思います。（Figmaを見て画面の作成ができる状態）

2024-09-30 02:15 UTC, ippei-shimizu commented
対応ありがとうございます。
画面遷移の流れは大まか確認できることを確認しました。
ただその流れを作るボタンやフォームなどが適切かもレビュー対象に含まれているため、お手数ですが以下の記事を参考に各ページをもう少し作り込んでください。

https://qiita.com/takakenhowaken/items/e525084c9e793b19c2ee

2024-10-02 02:01 UTC, woony-nam commented
画面遷移図、作り直しました。
ご確認お願いします。

### 画面遷移図
Figma https://www.figma.com/design/NHPyRC0mYvcfGcGRDGaaoN/%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB%E5%9B%B3?t=sk7egHOWbTx7VJl0-1

### READMEに記載した機能
- [x] 会員登録へ進むボタン
- [x] 20歳以上確認画面
　- Yes/No ボタン
- [x] 会員登録機能
- [x] ログイン機能へ進むボタン
　- ログイン機能
- [x] 投稿一覧
- [x] 新規投稿作成ページ
- [x] 検索機能（ 題名 or 銘柄 or UserName）
- [x] 検索結果ページ


### MVPリリース後に取り組む機能
- [x] 投稿詳細ページ
　- 翻訳機能
　- いいね機能
　- いいね解除機能
- [x] 投稿主のProfileページ
　- 翻訳機能
- [x] 検索機能（Tag）
- [x] 検索結果ページ
- [x] メニューバー
- [x] いいね履歴確認機能
　- いいね解除機能
- [x] My投稿一覧ページ
- [x] My投稿詳細ページ
- [x] My投稿編集ページ
　- 題名
　- 銘柄
　- 5段階評価の感想
　- 写真
　- Tag
　- コメント
　- 削除
- [x] MyProfile確認ページ
- [x] MyProfile編集ページ
　- UserName
　- Birthdate
　- ProfilePhoto
　- 一言ステータス
- [x] MyProfile編集内容確認ページ
- [x] 編集完了ページ
- [x] アカウント削除機能
- [x] MailAddress/Password 変更機能(＊)
- [x] 新規投稿作成ページ（写真/Tag/コメント）


### 未ログインでも閲覧または利用できるページ
日本酒（アルコール）を扱う内容なので、未ログインでも利用できるページはありません。

### メールアドレス・パスワード変更確認項目
直接変更できるものではなく、一旦メールなどを介して専用のページで変更する画面遷移にします。
- [x] メールアドレス
- [x] パスワード

### 各画面の作り込み
- [x] 作り込みはある程度完了していると思います。（Figmaを見て画面の作成ができる状態）

2024-10-03 03:07 UTC, kenchasonakai commented
LGTMです！

2024-10-15 07:19 UTC, merged